language: node_js

node_js:
    - "node"
    - "14"

sudo: false

git:
    submodules: false

before_script:
    - yarn

script:
  - yarn test:coverage

after_success:
    - yarn coveralls
    # - npm run report-codecov
